name: bt1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.10.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  http: ^1.2.1
  intl: ^0.19.0 
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  # THÊM: Thư viện tự động tạo icon app
  flutter_launcher_icons: ^0.13.1

# CẤU HÌNH ICON APP
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # sdk minimum cho dự án của bạn

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
